data:
  20news_group: ./resources/datasets/20news-bydate-train
  amazon_path: ./resources/datasets/amazon0302.txt.gz
  enron_path: ./resources/datasets/email-Enron.txt.gz
  rcv1_subset: train
  dataset_name: rcv1

output:
  results_dir: ./resources/excel/experiment_results.csv
  figures_dir: ./resources/plots

experiment:
  l_values: [50,60,70,80,90,100]
  k: 10
  slice_to: 3000
  rcv1_max_samples: 100000
  rcv1_max_features: 3000
  test_type: real